version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "23:00" # UTC time
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
